name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo snap install zig --classic --edge
            sudo docker pull williamyeh/wrk
            zig version
      - name: Module test
        run: zig build test
      - name: Parser test
        run: zig build parser_test
      - name: Build
        run: zig build -Doptimize=ReleaseSafe
